version: "3"
services:
  swagger:
    build:
      context: .
      dockerfile: ./docker/swagger/Dockerfile
    container_name: hoge # 好きなようにコンテナ名を追加してください
    volumes:
      - ./docker/swagger/swagger.yml:/usr/share/nginx/html/sample.yaml
    environment:
      API_URL: sample.yaml
    ports:
      - "3000:8080" # `http://localhost:3000/` で起動
